### ISSUE TITLE
what is weight momentum for conv layers in pkl file ?

### ISSUE THREAD

**Issue by Prakashvanapalli** [roytseng-tw/Detectron.pytorch#100]
I have downloaded the pickle file of RetinaNet pretrained from Detectron. When looking at the file and trying to map the weights to my pytorch model, for few layers of conv layer I see **weight_momentum** param. Not sure what this is 

```python
import pickle
with open("../weights/model_final.pkl", "rb") as fp:
    src_blobs = pickle.load(fp, encoding='latin1')
```

```python
for name, params in src_blobs["blobs"].items():
    if "res4_15_branch2c" in name:
        print(name, params.shape)
```

#Output 

```
res4_15_branch2c_w_momentum (1024, 256, 1, 1)
res4_15_branch2c_b (1024,)
res4_15_branch2c_w (1024, 256, 1, 1)
res4_15_branch2c_bn_s (1024,)
res4_15_branch2c_bn_b (1024,)
```

I understood that conv will have w and b params and bn will have s and b. Not sure what w_momentum is ? also not sure why it is added ? 

Thank you

**Comment by happyharrycn** [comment]
w_momentum is the internal state from the SGD optimizer. It is the momentum of w.

**Comment by Prakashvanapalli** [comment]
Okay.. got it . thank you.
