### ISSUE TITLE
Remuse training error

### ISSUE THREAD

**Issue by engineer1109** [roytseng-tw/Detectron.pytorch#109]
INFO train_net_step.py: 442: Save ckpt on exception ...
INFO train_net_step.py: 135: save model: Outputs/e2e_faster_rcnn_R-101-FPN_1x/Jul19-17-30-18_wjl-Precision-Tower-7810_step/ckpt/model_step296911.pth
INFO train_net_step.py: 444: Save ckpt done.
Traceback (most recent call last):
  File "tools/train_net_step.py", line 428, in main
    optimizer.step()
  File "/usr/local/lib/python3.5/dist-packages/torch/optim/sgd.py", line 101, in step
    buf.mul_(momentum).add_(1 - dampening, d_p)
RuntimeError: The expanded size of the tensor (1) must match the existing size (3) at non-singleton dimension 3

**Comment by Luodian** [comment]
I encountered the same problem when I continue to train ResNext-101 for coco dataset.
my gpus are 4 nvidia P40 in Telsa frame.

**Comment by iFighting** [comment]
i also have this error

**Comment by nickeleye** [comment]
I have a similar error 
RuntimeError: expand(torch.cuda.FloatTensor{[512, 512, 3, 3]}, size=[81, 2048]): the number of sizes provided (2) must be greater or equal to the number of dimensions in the tensor (4)
