### ISSUE TITLE
pytorch 0.4 support ?

### ISSUE THREAD

**Issue by soeaver** [roytseng-tw/Detectron.pytorch#11]
Hi, thanks for your great work!
I want to know that will Detectron.pytorch support pytorch>=0.4?

**Comment by roytseng-tw** [comment]
I haven't test is with pytorch verison newer than 0.3.1. However, I think everything should work just fine.
It's welcome that you report your usage results on newer versions of pytorch. For now, the latest release of pytorch is 0.3.1.

**Comment by Yuliang-Zou** [comment]
I think basically you remove all the `volatile`, then it should be fine.

**Comment by Frostinassiky** [comment]
Lots of errors came with Pytorch 0.4.0😏

**Comment by Liu0329** [comment]
#40 #18

**Comment by Liu0329** [comment]
Hi guys, I have built a pytorch 0.4 branch: https://github.com/Liu0329/Detectron.pytorch/tree/pytorch-0.4.
I have tested it on my machine. Please let me know if there are still problems.

**Comment by roytseng-tw** [comment]
Support pytorch0.4 and close the issue ~
