### ISSUE TITLE
Why there is no ReLU in FPN output

### ISSUE THREAD

**Issue by bowenc0221** [roytseng-tw/Detectron.pytorch#114]
Hi @roytseng-tw ,

Thanks for the nice work.
I have a question about the FPN code: why there is no ReLU activation in the Post-hoc scale-specific 3x3 convolutions as well as the lateral connection?

**Comment by roytseng-tw** [comment]
First of all, there is no ReLU there in Detectron's FPN implementation either.
Here's my opinion on why:
1. post-hoc scale-specific 3x3 convs: the outputs are used to extract roi features, so it's better to be dense.
2. lateral convs: the outputs are fused with the features one-level above, so you want them to have same kind of distribution.

**Comment by ppwwyyxx** [comment]
This exact question is answered in the paper already:
>  There are no non-linearities in these extra layers,
which we have empirically found to have minor impacts

**Comment by bowenc0221** [comment]
Thanks!
