### ISSUE TITLE
UnicodeDecodeError when using COCO pre-trained Detectron models

### ISSUE THREAD

**Issue by AruniRC** [roytseng-tw/Detectron.pytorch#116]
I have been trying to run `infer_simple.py` using a COCO pre-trained model downloaded from the Detectron [Model Zoo](https://github.com/facebookresearch/Detectron/blob/master/MODEL_ZOO.md#end-to-end-faster--mask-r-cnn-baselines).  

The current repo uses Python3, while Detectron models originally were saved as pkl files using Python2. This may be a possible reason for the following error:

```
Called with args:
Namespace(cfg_file='configs/baselines/e2e_faster_rcnn_R-50-C4_1x.yaml', cuda=True, dataset='coco', image_dir='demo/sample_images', images=None, load_ckpt='data/detectron_trained_model/e2e_faster_rcnn_R-50-C4_1x.pkl', load_detectron=None, merge_pdfs=True, output_dir='demo/sample_images_mask-rcnn', set_cfgs=[])
load cfg from file: configs/baselines/e2e_faster_rcnn_R-50-C4_1x.yaml
loading checkpoint data/detectron_trained_model/e2e_faster_rcnn_R-50-C4_1x.pkl
......
......
  File "/home/arunirc/anaconda2/envs/detectron-video/lib/python3.6/site-packages/torch/serialization.py", line 410, in _load
    magic_number = pickle_module.load(f)
UnicodeDecodeError: 'ascii' codec can't decode byte 0x95 in position 6: ordinal not in range(128)
```

It would be nice to have some support of using existing COCO pre-trained models from the Detectron Model Zoo ..

**Comment by asediri** [comment]
Hello @AruniRC ! 
Have you managed to solve the problem ?
Thank you in advance for your answer.
