### ISSUE TITLE
Fine-tuning on Detectron pre-trained weights

### ISSUE THREAD

**Issue by Yuliang-Zou** [roytseng-tw/Detectron.pytorch#12]
Thanks for the great work! 

I wonder if I can load pre-trained weights from Detectron and fine-tune it with this code?

**Comment by roytseng-tw** [comment]
Yes. You can load pre-trained weights from Detectron by `train_net.py --load_detectron /path/to/the/weight/file ...`.  Notice that you may want to adjust the learning rate.

**Comment by Yuliang-Zou** [comment]
@roytseng-tw It seems if we fine-tune the model using Detectron weights and apply learning rate decay, there will be a KeyError when correct the momentum.

```
File "/home/ylzou/research/Detectron.pytorch/lib/utils/net.py", line 80, in _CorrectMomentum
optimizer.state[p_key]['momentum_buffer'] *= correction
KeyError: 'momentum_buffer'
```
