### ISSUE TITLE
python2 support problem

### ISSUE THREAD

**Issue by CoinCheung** [roytseng-tw/Detectron.pytorch#126]
### Expected results

python2 have problem with logging model and lib/utils/logging.py

### Actual results

when I use python2, the output error log is: 
```
Traceback (most recent call last):
  File "tools/train_net.py", line 23, in <module>
    import utils.net as net_utils
  File "/data/zhangzy/projects/NoMan/Detectron.pytorch/lib/utils/net.py", line 12, in <module>
    logger = logging.getLogger(__name__)
AttributeError: 'module' object has no attribute 'getLogger'
```

### Detailed steps to reproduce

```
    $ cd Detectron.pytorch
    $ python2 tools/tain_net.py -cfg configs/....yaml
```

### System information

* Operating system: ubuntu16.04
* CUDA version: 9.1
* cuDNN version: 7
* GPU models (for all devices if they are not all the same): 1080
* python version: 2.7
* pytorch version: 0.4.0
* Anything else that seems relevant: ?

**Comment by CoinCheung** [comment]
Same problem seems with lib/utils/collections.py and collections.

**Comment by ncherel** [comment]
Yes, the code is for python3.

From the README:
>Tested under python3.

See also https://github.com/roytseng-tw/Detectron.pytorch/issues/88#issuecomment-398962523

**Comment by CoinCheung** [comment]
Yes I switched to python3, and it has no python version problems anymore. Many thanks.
