### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0x95 in position 6: ordinal not in range(128)

### ISSUE THREAD

**Issue by daijucug** [roytseng-tw/Detectron.pytorch#130]

**Comment by daijucug** [comment]
File "/home/daiju/mask-rcnn.pytorch/tools/infer_simple.py", line 129, in main
    checkpoint = torch.load(load_name, map_location=lambda storage, loc: storage, pickle_module=cPickle)
  File "/home/daiju/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 267, in load
    return _load(f, map_location, pickle_module)
  File "/home/daiju/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 410, in _load
    magic_number = pickle_module.load(f)
UnicodeDecodeError: 'ascii' codec can't decode byte 0x95 in position 6: ordinal not in range(128)

**Comment by triangleCZH** [comment]
Hi, I'm also facing this problem. May I ask if you have figure out a reason for the problem?

**Comment by QUJIJI** [comment]
@triangleCZH @daijucug 
Hi, I'm also facing this problem. Could you tell me how do you solve it?

**Comment by QUJIJI** [comment]
solved. https://github.com/roytseng-tw/Detectron.pytorch/issues/76

**Comment by ShaiLimonchik** [comment]
Hi, I'm getting the same error but I am using train_net.py and thus can't use the --load_detectron flag as in #76.
Any ideas?
