### ISSUE TITLE
Cannot test with the pre-trained Detectron model?

### ISSUE THREAD

**Issue by baiyancheng20** [roytseng-tw/Detectron.pytorch#142]
I use the following commands for inferring:
`python tools/infer_simple.py --dataset coco --cfg ./configs/baselines/e2e_faster_rcnn_R-50-C4_2x.yaml --load_detectron ./model_final.pkl --image_dir ./demo/sample_images --output_dir ./demo/`

I got the following error:
`p_tensor.copy_(torch.Tensor(src_blobs[d_name]))
KeyError: 'conv_rpn_w'`

I checked the **src_blobs** in **detectron_weight_helper.py** and I found the key and value of 'conv_rpn_w' didn't exit.
Could you help me deal with this?

* Operating system: Ubuntu 16.04
* CUDA version: 8
* cuDNN version: 7
* GPU models (for all devices if they are not all the same): 1080t9
* python version: 3.6
* pytorch version: 0.4
* Anything else that seems relevant: ?

**Comment by baiyancheng20** [comment]
Problem has been solved. Download the wrong model.

**Comment by XPandora** [comment]
Hi, I have the same problem, can you give a correct model link?

**Comment by MindyZLM** [comment]
@XPandora  Hi, I have the same problem,can you tell me how to solve it? thanks!
