### ISSUE TITLE
importerror: no deafultdict

### ISSUE THREAD

**Issue by cherryxiongyw** [roytseng-tw/Detectron.pytorch#15]
When i run imfer_simple.py, I meet this error in "utils/misc.py" in line 
`from collections import defaultdice,Iterable`
so how to solve this problem?

**Comment by roytseng-tw** [comment]
Did you use python 2 or 3 ?
It seems that utils/collections.py shadow the collections package in python standard library.

**Comment by oujieww** [comment]
@roytseng-tw  ,thank u ,yes, i use python 2 ,i find collections  in python standard library but in lib/utils/ also have a collections so what should i do?

**Comment by roytseng-tw** [comment]
It's recommend to use python3 for this code. However, add the line `from __future__ import absolute_import` to the top of `lib/utils/collections.py` can solve this particular issue, but you probably will encounter another issue afterwards. Hence, the recommended way is to setup a virtual environment for python3.
