### ISSUE TITLE
What is "detectron_weight_mapping" for?

### ISSUE THREAD

**Issue by bowenc0221** [roytseng-tw/Detectron.pytorch#154]
Could anyone explain what "detectron_weight_mapping" for?  
It seems it is only used to "filter" some weights when loading a model in [here](https://github.com/roytseng-tw/Detectron.pytorch/blob/master/lib/utils/net.py#L156-L163).

Thanks.

**Comment by achalddave** [comment]
I think it's primarily to map the caffe2 detectron model keys to the pytorch detectron model parameter names, e.g. [here](https://github.com/roytseng-tw/Detectron.pytorch/blob/8315af319cd29b8884a7c0382c4700a96bf35bbc/lib/utils/detectron_weight_helper.py#L9) and throughout [here](https://github.com/roytseng-tw/Detectron.pytorch/blob/8315af319cd29b8884a7c0382c4700a96bf35bbc/lib/utils/resnet_weights_helper.py)
