### ISSUE TITLE
Unable to Properly Load Classes

### ISSUE THREAD

**Issue by jameschartouni** [roytseng-tw/Detectron.pytorch#16]
I am trying to train a model using a custom JSON dataset that I converted to the COCO format. I've adapted the code given in train.py, but I am unable to load the classes properly. Regardless of what number of classes I specify in the config file, I am getting this same error. Is there an obvious mistake that I am making? Thank you!

```
timers = defaultdict(Timer)

### Dataset ###
timers['roidb'].tic()
roidb, ratio_list, ratio_index = combined_roidb_for_training(cfg.TRAIN.DATASETS, cfg.TRAIN.PROPOSAL_FILES)
timers['roidb'].toc()
train_size = len(roidb)
logger.info('{:d} roidb entries'.format(train_size))
logger.info('Takes %.2f sec(s) to construct roidb', timers['roidb'].average_time)

sampler = MinibatchSampler(ratio_list, ratio_index)
dataset = RoiDataLoader(
    roidb,
    cfg.MODEL.NUM_CLASSES,
    training=True)
dataloader = torch.utils.data.DataLoader(
    dataset,
    batch_size=args.batch_size,
    sampler=sampler,
    num_workers=cfg.DATA_LOADER.NUM_THREADS,
    collate_fn=collate_minibatch)

assert_and_infer_cfg()

```
The output:

```
INFO:datasets.json_dataset:Loading cached gt_roidb from /home/cees2/Image Project/Code/mask-rcnn.pytorch/data/cache/init_data_gt_roidb.pkl
INFO:datasets.roidb:Appending horizontally-flipped training examples...
INFO:datasets.roidb:Loaded dataset: init_data
INFO:datasets.roidb:Filtered 120 roidb entries: 120 -> 0
INFO:datasets.roidb:Computing image aspect ratios and ordering the ratios...
INFO:datasets.roidb:done
INFO:datasets.roidb:Computing bounding-box regression targets...
INFO:datasets.roidb:done
loading annotations into memory...
Done (t=0.01s)
creating index...
index created!
[]
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-4-f5a66a92f826> in <module>()
      3 ### Dataset ###
      4 timers['roidb'].tic()
----> 5 roidb, ratio_list, ratio_index = combined_roidb_for_training(cfg.TRAIN.DATASETS, cfg.TRAIN.PROPOSAL_FILES)
      6 timers['roidb'].toc()
      7 train_size = len(roidb)

~/Image Project/Code/mask-rcnn.pytorch/lib/datasets/roidb.py in combined_roidb_for_training(dataset_names, proposal_files)
     77     logger.info('done')
     78 
---> 79     _compute_and_log_stats(roidb)
     80 
     81     return roidb, ratio_list, ratio_index

~/Image Project/Code/mask-rcnn.pytorch/lib/datasets/roidb.py in _compute_and_log_stats(roidb)
    229 def _compute_and_log_stats(roidb):
    230     print(roidb)
--> 231     classes = roidb[0]['dataset'].classes
    232     char_len = np.max([len(c) for c in classes])
    233     hist_bins = np.arange(len(classes) + 1)

IndexError: list index out of range
```

**Comment by roytseng-tw** [comment]
Notice this line: `INFO:datasets.roidb:Filtered 120 roidb entries: 120 -> 0`
All of your images are filtered out, because none them have usable RoIs based on config settings
Check [here](https://github.com/roytseng-tw/Detectron.pytorch/blob/master/lib/datasets/roidb.py#L119)  for filtering mechanism.

**Comment by jameschartouni** [comment]
Thank you! The quick reply is really appreciated. I'll try to dig down and see what's the core problem.

**Comment by jameschartouni** [comment]
Why is it filtering out all of the ROIDB entries? Regardless of how I alter the config settings related to the is_valid function in roidb, all my targets get filtered. I've gone through my json file and am able to properly visualize the masks.

**Comment by roytseng-tw** [comment]
https://github.com/roytseng-tw/Detectron.pytorch/blob/master/lib/datasets/json_dataset.py#L141
When load a data for the first time, JsonDataset will cache the gt roidb to a pickle file, located in `data/cached/` by default. Afterwards, the gt roidb will be loaded from the pickle file instead of json file to save about 20 secs for coco_2017_train. 
It's probably that you are not using the updated version of your annotation. Either deleting the cached pickle file or commenting out corresponding lines about caching will fix that.

**Comment by jameschartouni** [comment]
Thank you! Deleting the pickle file in cache worked.

**Comment by ash1995** [comment]
I'm facing the same issue while dealing with satellite images. Could you tell me how you fixed your problem and what were the config settings that control the is_valid function in roidb.py?
