### ISSUE TITLE
Dataloader throws error during iter()

### ISSUE THREAD

**Issue by tobyclh** [roytseng-tw/Detectron.pytorch#18]
Hello, I'm trying to get the repo to work with PyTorch 0.4.
While most of the changes are rather trivial, the sampler this repo uses, return both index and aspect ratio (correct me if it is something else, but it is a tuple and the batch sampler assume integer), there isn't any straightforward way to fix it with the new dataloader structure introduced in pytorch/pytorch#1867.
What would you think is the better way to make it compatible without breaking anything?
Thank you

**Comment by roytseng-tw** [comment]
I am a little confused. Doesn't same batch sampler exists in PyTorch 0.3.1 ?

**Comment by roytseng-tw** [comment]
I see. The explicit int cast is the evil. A straight forward way to overcome this problem is providing a BatchSampler that do not cast the items from Sampler.
