### ISSUE TITLE
Why does mynn.DataParallel not support multiple gpus?

### ISSUE THREAD

**Issue by ashnair1** [roytseng-tw/Detectron.pytorch#209]
In infer_simple.py the mask RCNN model is created as follows: 
```
maskRCNN = mynn.DataParallel(maskRCNN, cpu_keywords=['im_info', 'roidb'],
                                 minibatch=True, device_ids=[0])  # only support single GPU
```

I've noticed that the DataParallel module only supports a single GPU. I actually wanted to speed up my inference time i.e. time taken to visualise the detections of the model on an image since I have upward of 1000 images. Is there a way to visualise and save the detections on multiple images using multiple gpus? Also why can't the model support multiple GPUs?

**Comment by 1179021477** [comment]
Excuse me, have  you solved this problem?

**Comment by ashnair1** [comment]
No, I actually just moved onto detectron2
