### ISSUE TITLE
cuda runtime error: out of memory after 15K iteration of 4 GPUs training

### ISSUE THREAD

**Issue by JackHenry1992** [roytseng-tw/Detectron.pytorch#22]
Hi, @roytseng-tw, I have successfully ran train_net.py of resnet-C4 (using 4 GPUs), but after 15K training steps, `cuda runtime error with out of memory`.

![image](https://user-images.githubusercontent.com/9390228/39105033-e3c364ba-46e5-11e8-9247-c5411f8a9c43.png)

![image](https://user-images.githubusercontent.com/9390228/39104857-e4889060-46e4-11e8-9b46-d37c7d175bb4.png)

As I thought, this was caused by the increasing GPU-memory of  dynamic graph, such as `loss+=xxx`, can you give some advices for solving this issue.

**Comment by roytseng-tw** [comment]
What's your training command and gpu memory size?

**Comment by JackHenry1992** [comment]
I have retraining resnet50-FPN-2x using 4 Tesla-P40 GPUs, and each GPU is 20GB memory (total batchsize is setted to 5).
The initial memory occupation is:
![image](https://user-images.githubusercontent.com/9390228/39162357-b93ca004-47a7-11e8-88f8-53fc9c5a2a56.png)

After 1.99k iterations:
![image](https://user-images.githubusercontent.com/9390228/39162373-c72f6a0c-47a7-11e8-8f29-671480c11952.png)

There is the memory details after 16k iterations
![image](https://user-images.githubusercontent.com/9390228/39162214-fd58596e-47a6-11e8-8bd2-727f8ca84a12.png)

The memory is increased, but the memery occupation of GPU 2 is strange. I can't figure this error.
In addition, I have modified `loss_avg+=loss.data[0]` to use the float type

**Comment by roytseng-tw** [comment]
Actually that line has been changed to `loss_avg += loss.data.cpu().numpy()[0]` for a while.
BTW, what do mean by "modified loss_avg+=loss.data[0] to use the float type" ?

**Comment by JackHenry1992** [comment]
Refer to [Confused about loss.data](https://discuss.pytorch.org/t/confused-about-loss-data-0/1572), what is the effect of `loss_avg += loss.data.cpu().numpy()[0]` ?

**Comment by roytseng-tw** [comment]
Is seems that the shorter code `loss_avg+=loss.data[0]`  is enough to avoid “keeping track over everything” problem.
And what do you mean by " ... **which may increase the memory** ", I don't get the point.

**Comment by JackHenry1992** [comment]
I follow the [CUDA memory continuously increases when net(images) called in every iteration](https://discuss.pytorch.org/t/cuda-memory-continuously-increases-when-net-images-called-in-every-iteration/501), but not sure whether it's useful....

**Comment by roytseng-tw** [comment]
My implementation do not have problem mentioned above. So actually you didn't really change anything. BTW, rcnn will not have stabe gpu memory footprint through out the training, and 4 gpus training of batch size 5 for each is risky.

**Comment by GuoleiSun** [comment]
@JackHenry1992, I meet the same problem.
I have only one GPU (TiTan Xp, Memory size: 12G) and the batch size is 1.
Any insights to solve the problem with my configurations?
Thanks
