### ISSUE TITLE
ImportError using Pytorch 1.1.0

### ISSUE THREAD

**Issue by nQuant** [roytseng-tw/Detectron.pytorch#226]
Import Error using Pytorch 1.1.0

I encountered this error during a dataset conversion to COCO json format

```
----> 6 from lib.utils.boxes import xyxy_to_xywh
.
.
.
/content/Detectron.pytorch/lib/nn/parallel/scatter_gather.py in <module>()
      6 from ._functions import Scatter, Gather
      7 from torch._six import string_classes, int_classes
----> 8 from torch.utils.data.dataloader import numpy_type_map
      9 
     10 

ImportError: cannot import name 'numpy_type_map'
```

It seems that _numpy_type_map_ has been moved to torch/utils/data/_utils/collate.py in pytorch 1.1.0

Maybe _numpy_type_map_ should be redefined entirely instead of being imported.

**Comment by nQuant** [comment]
Issue posted in the wrong fork.

**Comment by yestinl** [comment]
I encountered the same question. How did you solve it?

**Comment by nQuant** [comment]
I was using this fork that support Pytorch 1.1+ / torchvision 0.3.0+ with Python 3:
https://github.com/adityaarun1/Detectron.pytorch
The reported issue is now solved for this fork.

You may also consider to use Detectron2 for Pytorch 1.3+/ Python3.6+ instead.
