### ISSUE TITLE
Hi roytseng, I'd like to put a project based on your 'Detectron.pytorch' project to my Github reposity, could I?

### ISSUE THREAD

**Issue by tasselcui** [roytseng-tw/Detectron.pytorch#25]
Inspired by '4K Video Demo by Karol Majek' at https://github.com/matterport/Mask_RCNN#projects-using-this-model, and based on your 'Detectron.pytorch' project, I built a toy project. 
Compared Karol Majek's, my project blent human masks and human keypoints together, it seemed funny, so I'd like to put a project based on your 'Detectron.pytorch' project to my Github reposity, could I?
The demo video is below.
Could you visit this demo video at 'youku.com'?http://v.youku.com/v_show/id_XMzU2MDYyNDQ5Mg==.html?spm=a2hzp.8244740.0.0
Looking forward to hearing from you soon.

**Comment by roytseng-tw** [comment]
Of course, you are welcome to use this project to build your own project. 😄

**Comment by tasselcui** [comment]
thanks.
