### ISSUE TITLE
Do you have plans to support R-FCN or Light-Head-RCNN?

### ISSUE THREAD

**Issue by hewumars** [roytseng-tw/Detectron.pytorch#27]
Do you have plans to support R-FCN or Light-Head-RCNN?

**Comment by roytseng-tw** [comment]
No plan for now. However, pull requests are welcome !

**Comment by hewumars** [comment]
@roytseng-tw why set 'RPN:CLS_ACTIVATION: softmax' in yml file is error ？

 rpn_cls_prob = rpn_cls_prob[:, 1].view(B, C // 2, H, W)
RuntimeError: invalid argument 2: size '[1 x 15 x 50 x 50]' is invalid for input with 2500 elements at /pytorch/torch/lib/TH/THStorage.c:41

**Comment by roytseng-tw** [comment]
Hi, it has been fixed now.
