### ISSUE TITLE
Don't have good results when use pre-trained Detectron model

### ISSUE THREAD

**Issue by cherryxiongyw** [roytseng-tw/Detectron.pytorch#41]
When I run infer_simple.py with pre-trained Detectron model, I don't have good results. The command is like as:
`python3 tools/infer_simple.py --dataset coco --cfg configs/e2e_mask_rcnn_R-101-FPN_2x.yaml --load_detectron configs/e2e_mask_rcnn_R-101-FPN_2x.pkl --image_dir demo/sample_images  --output_dir demo/out`, 
the scores of objects are very low as 0.08, I can't get accurate results.
So what's wrong?

**Comment by roytseng-tw** [comment]
To be sure, what's the model id that you take the pretrained weightd from ?

**Comment by cherryxiongyw** [comment]
The model id is 35861858

**Comment by roytseng-tw** [comment]
My results are correct. Have you change anything and what's the version of code you are using ?

**Comment by cherryxiongyw** [comment]
I don't change anything and I don't know why, but when I update the codes today, I get the correct results. Anyway, thank you very much.

**Comment by roytseng-tw** [comment]
Good to hear that ! closing the issue~~
