### ISSUE TITLE
Support for different class ckpt loaded?

### ISSUE THREAD

**Issue by QiaoranC** [roytseng-tw/Detectron.pytorch#42]
Hi:
I used a customized dataset with class=3, the training is fine and the ckpt can be generated.
But, when comes to test,  there is a problem when loaded the ckpt: ckpt and model's output dimension not match. 

`maskRCNN = Generalized_RCNN()` based on assume class 81(coco class) and my ckpt is based on class3.

What i usually do is change the the output layer of model to fit different class. But the mask rcnn is more complicated than a "normal" model.

**So Could you show me which layers should be changed to fit the customized num_class?**

`RuntimeError: While copying the parameter named Mask_Outs.classify.weight, whose dimensions in the model are torch.Size([81, 256, 1, 1]) and whose dimensions in the checkpoint are torch.Size([3, 256, 1, 1]).`

Thanks

**Comment by QiaoranC** [comment]
My mistake, forget the change the num_class in test.

**Comment by liaozp1** [comment]
HI:
can u tell me how to train on a customized dataset?i have problem with it,could u help me? thx
