### ISSUE TITLE
Simple demo.py file for an example usage

### ISSUE THREAD

**Issue by IssamLaradji** [roytseng-tw/Detectron.pytorch#44]
Do you have a simple `demo.py` file that allows you to load a pretrained model and predict on a single example image ?

Thanks.

**Comment by roytseng-tw** [comment]
Yes, checkout `infer_simple.py`

**Comment by vsd550** [comment]
But for infer_simple.py we need checkpoints or detectron weights, for which we will have to train the model from scratch. Please correct me if I am wrong. Thanks
