### ISSUE TITLE
Error at testing with Detectron pretrained ResNet-50 architecture 

### ISSUE THREAD

**Issue by cgokce** [roytseng-tw/Detectron.pytorch#47]
### Expected results

I was trying to test Detectron ResNet50 architecture with pretrained caffe weights on COCO-Val 2017 set and got the error below.

Update: Detectron repo updated with "group batch norm" feature 12 days ago. (https://github.com/facebookresearch/Detectron/tree/master/configs/04_2018_gn_baselines) I believe they also changed model files and only providing pkl files for new baselines (https://github.com/facebookresearch/Detectron/blob/master/MODEL_ZOO.md). If my assumption is true, can you upload previous .pkl files to some place, so that we can continue using your implementation in pytorch?

### Actual results
```
loading annotations into memory...
Done (t=0.70s)
creating index...
index created!
loading annotations into memory...
Done (t=0.93s)
creating index...
index created!
INFO test_engine.py: 335: loading detectron weights data/pretrained_model/R-50.pkl
Traceback (most recent call last):
  File "tools/test_net.py", line 112, in <module>
    check_expected_results=True)
  File "/home/john/Desktop/cvav_proj/detectorn_roytseng/mask-rcnn.pytorch/lib/core/test_engine.py", line 128, in run_inference
    all_results = result_getter()
  File "/home/john/Desktop/cvav_proj/detectorn_roytseng/mask-rcnn.pytorch/lib/core/test_engine.py", line 108, in result_getter
    multi_gpu=multi_gpu_testing
  File "/home/john/Desktop/cvav_proj/detectorn_roytseng/mask-rcnn.pytorch/lib/core/test_engine.py", line 158, in test_net_on_dataset
    args, dataset_name, proposal_file, output_dir, gpu_id=gpu_id
  File "/home/john/Desktop/cvav_proj/detectorn_roytseng/mask-rcnn.pytorch/lib/core/test_engine.py", line 232, in test_net
    model = initialize_model_from_cfg(args, gpu_id=gpu_id)
  File "/home/john/Desktop/cvav_proj/detectorn_roytseng/mask-rcnn.pytorch/lib/core/test_engine.py", line 336, in initialize_model_from_cfg
    load_detectron_weight(model, args.load_detectron)
  File "/home/john/Desktop/cvav_proj/detectorn_roytseng/mask-rcnn.pytorch/lib/utils/detectron_weight_helper.py", line 21, in load_detectron_weight
    p_tensor.copy_(torch.Tensor(src_blobs[d_name]))
KeyError: 'fpn_inner_res5_2_sum_w'
```

### Detailed steps to reproduce

I've downloaded ResNet-50 model file from Detectron github page (https://s3-us-west-2.amazonaws.com/detectron/ImageNetPretrained/MSRA/R-50.pkl).

The command I've ran is here

```
python tools/test_net.py --dataset coco2017 --cfg configs/e2e_mask_rcnn_R-50-FPN_1x.yaml --load_detectron data/pretrained_model/R-50.pkl
```

Also I get `KeyError: 'conv_rpn_w'` when i change config to R-50-C4_1x or R-50-C4_2x files.

### System information

* Operating system: Ubuntu 16.04
* CUDA version: 9
* cuDNN version: ?
* GPU models (for all devices if they are not all the same): 1050 Ti
* python version: 3.6.4 (Anaconda custom)
* pytorch version: 0.3.4
* Anything else that seems relevant: ?

**Comment by roytseng-tw** [comment]
You used the wrong pickle weight file. You should use the one correspond to `e2e_mask_rcnn_R-50-FPN_1x.yaml`.
And this repo does not provide the functionality to evaluate a single backbone architecture.

**Comment by enderhsu** [comment]
HI @roytseng-tw , can you kindly tell me where is the corresponding weight file for 2e_mask_rcnn_R-50-FPN_1x.yaml? Because R-50 is the only one I can found...

**Comment by dangkhoasdc** [comment]
@enderhsu : Here is the link of the corresponding weights: [Download](https://s3-us-west-2.amazonaws.com/detectron/36225401/12_2017_baselines/mask_rcnn_R-50-FPN_1x.yaml.08_42_04.MocEgrRW/output/train/coco_2014_train%3Acoco_2014_valminusminival/generalized_rcnn/model_final.pkl)

Source: https://github.com/facebookresearch/Detectron/blob/master/MODEL_ZOO.md , make sure that you download the weight which matches with the config.
