### ISSUE TITLE
mismatch of shape while loading from .pkl file

### ISSUE THREAD

**Issue by shridharkini6** [roytseng-tw/Detectron.pytorch#51]
I tried inference with e2e_keypoint_rcnn_R-50-FPN_s1x.yaml using pkl file available from Detectron @https://github.com/facebookresearch/Detectron/blob/master/MODEL_ZOO.md

CUDA :9.0
GPU: K80
Pytorch: 0.4.0
python:2.7

Got this error:
> File "tools/infer_simple.py", line 176, in <module>
>     main()
>   File "tools/infer_simple.py", line 128, in main
>     load_detectron_weight(maskRCNN, args.load_detectron)
>   File "/home/tester/detectron/mask-rcnn.pytorch/lib/utils/detectron_weight_helper.py", line 22, in load_detectron_weight
>     p_tensor.copy_(torch.Tensor(src_blobs[d_name]))
> RuntimeError: The expanded size of the tensor (81) must match the existing size (2) at non-singleton dimension 0

**Comment by roytseng-tw** [comment]
First of all, this repo only supports python3 and doesn't update to pytorch 0.4 yet.

**Comment by roytseng-tw** [comment]
Judging from the error message, I think you were using the wrong config file: num_classes is 81 for mask/faster-rcnn, and is 2 for keypoint-rcnn.
