### ISSUE TITLE
A trouble to understand the attribute of "training" of the class "CollectAndDistributeFpnProposalOp()

### ISSUE THREAD

**Issue by wmmxk** [roytseng-tw/Detectron.pytorch#52]
I was running the "test_net.py". In the /lib/modeling/FPN.py file, there is such a line "self.CollectAndDistributeFpnRpnProposals = CollectAndDistributeFpnRpnProposalsOp()" in the constructor of the "fpn_rpn_outputs" class. Since the CollectAndDistributeFpnRpnProposalsOp class inherits the nn.module which has an attribute named "training" and it is "True" by default, so the CollectAndDistributeFpnRpnProposals object's "training" attribute is also "True".

But when I print out the "self.CollectAndDistributeFpnRpnProposals.training" in the "forward" function of the "fpn_rpn_outputs" class, I saw a "False". 

Do you know when the "training" attribute of the CollectAndDistributeFpnRpnProposals object is set to be False?

**Comment by roytseng-tw** [comment]
It should be `False` on testing and `True` on training. It'll be `False` on testing because `maskRCNN.eval()`.
