### ISSUE TITLE
Python 2 support

### ISSUE THREAD

**Issue by taoari** [roytseng-tw/Detectron.pytorch#53]
Will you add Python 2 support for this repo? In general, I have done the following three things to make the infer_simple.py script work for python2.

1. fix super: `3to2 -f super -w .`
2. rename `utils.collections` to `utils.collections2` to avoid conflicting with the official collections library
3. `pickle.load(fp, encoding='latin1')` -> `pickle.load(fp)`

An example repo is at https://github.com/taoari/Detectron.pytorch/commits/dev, will you add full support of this repo for python 2?

**Comment by roytseng-tw** [comment]
Hi, I have no plan to add fully support for python2 because I don't have time :cry:
BTW, to solve problem2, it's better to do this way: `from __future__ import absolute_import`
