### ISSUE TITLE
A trouble to understand the __getitem__ method in  RoiDataLoader class

### ISSUE THREAD

**Issue by wmmxk** [roytseng-tw/Detectron.pytorch#55]
I am trying to understand the signature of the "__getitem__"  method of the "RoiDataLoader" class in the /lib/roi_data/loader.py file. That class is a subclass of the abstract class "dataset" in pytorch. In the definition of "dataset" in pytorch, the "__getitem__" method supports integer indexing in range from 0 to len(self) exclusive. But for the RoiDataLoader, the parameter for "__getitem__" method is an index_tuple. Could you explain how it works?

Thanks.

**Comment by wmmxk** [comment]
Does anyone have any ideas about how to move forward to understand the "__getitem__" method?

**Comment by roytseng-tw** [comment]
`__getitem__`'s input arguments are given from sampler, and the sampler I use is `MinibatchSampler`.
`MinibatchSampler` is a generator that yields a tuple of (ratio, index), so dataset's `__getitem__` will receive a tuple instead of a single int. That's it.

**Comment by wmmxk** [comment]
Thanks Roytseng for your reply. I just figured out. Yes, __getitem__ method allows a tuple as an index(see the link at the end). The definition of the __next__ method of  DataLoaderIter in pytorch is like this: 
    def __next__(self):
        if self.num_workers == 0:  # same-process loading
            indices = next(self.sample_iter)  # may raise StopIteration
            batch = self.collate_fn([self.dataset[i] for i in indices])
So the self.sample_iter is the MinibatchSampler in our context.

https://stackoverflow.com/questions/1685389/possible-to-use-more-than-one-argument-on-getitem?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

Roytseng, you can close this issue now if you like. Thanks again.
