### ISSUE TITLE
undefined symbol: _Py_Dealloc

### ISSUE THREAD

**Issue by hcx1231** [roytseng-tw/Detectron.pytorch#58]
when i ran:
python tools/test_net.py

got this error:

ImportError: /home/work/hcx/Detectron.pytorch/lib/model/roi_pooling/_ext/roi_pooling/_roi_pooling.so: undefined symbol: _Py_Dealloc

python 3.5
pytorch 0.4

**Comment by roytseng-tw** [comment]
Have you compile the code ?

**Comment by hcx1231** [comment]
i have compiled @roytseng-tw

**Comment by roytseng-tw** [comment]
Did you use roi_pooling? If not, you can try comment out corresponding lines for roi_pooling in `lib/modeling/model_builder.py`

**Comment by hcx1231** [comment]
I pulled your latest code and it ran ok,thank you @roytseng-tw

**Comment by roytseng-tw** [comment]
But actually I didn't change anything related to this. Anyway, glad to hear that.

**Comment by zimenglan-sysu-512** [comment]
hi @hcx1231 
have u solved this problem?
