### ISSUE TITLE
Help with finetuning on custom dataset

### ISSUE THREAD

**Issue by yimang** [roytseng-tw/Detectron.pytorch#60]
Hi, I am trying to finetune the ```e2e_mask_rcnn_R-101-FPN_2x``` pretrained detectron model on a custom dataset with a different number of classes.

So far I've done these steps:
1. Converted my dataset to COCO format and placed annotations/images folders appropriately.
2. Added my dataset info to ```lib/datasets/dataset_catalog.py```.
3. Added command line arg to point to dataset in ```tools/train_net_step.py```.
4. Modified ```e2e_mask_rcnn_R-101-FPN_1x_d2s.yaml``` to my specifications.

There doesn't seem to be an issue when I'm training from scratch with Imagenet weights. However, when I try to to finetune with 

```
python tools/train_net_step.py --dataset custom_data --cfg experiments/e2e_mask_rcnn_R-101-FPN_1x_custom_data.yaml --load_detectron detectron/e2e_mask_rcnn_R-101-FPN_2x/model_final.pkl --use_tfboard --bs 3
```

I get this error: 

```
INFO train_net_step.py: 318: loading Detectron weights .../mask-rcnn.pytorch/detectron/e2e_mask_rcnn_R-101-FPN_2x/model_final.pkl
Traceback (most recent call last):
  File "tools/train_net_step.py", line 439, in <module>
    main()
  File "tools/train_net_step.py", line 319, in main
    load_detectron_weight(maskRCNN, args.load_detectron)
  File ".../mask-rcnn.pytorch/lib/utils/detectron_weight_helper.py", line 21, in load_detectron_weight
    p_tensor.copy_(torch.Tensor(src_blobs[d_name]))
RuntimeError: invalid argument 2: sizes do not match at /opt/conda/conda-bld/pytorch_1518243271935/work/torch/lib/THC/generic/THCTensorCopy.c:51
```

I imagine I need to reinitialize the output layers for class predictions to the correct size for my dataset, but I haven't figured out how. Any help would be appreciated as I am inexperienced with pytorch. Thanks!

### System information

* Operating system: Ubuntu 14.04.05 LTS
* CUDA version: 8
* cuDNN version: 6
* GPU models: GTX 1080 Ti
* python version: 3.6.3
* pytorch version: 0.3.1

**Comment by roytseng-tw** [comment]
Then you should not load the pretrained weights for the last output layers, whose output dimensions are affected by number of classes. Just set the corresponding weight mapping entries to `None`.

**Comment by yimang** [comment]
Thanks for the advice! 

Update: I wasn't too sure what the names of the last output layers were, so I modified the ```load_detectron_weight``` function in ```lib/utils/detectron_weight_helper.py``` by adding a try-except block:

```Python
def load_detectron_weight(net, detectron_weight_file):
    name_mapping, orphan_in_detectron = net.detectron_weight_mapping

    with open(detectron_weight_file, 'rb') as fp:
        src_blobs = pickle.load(fp, encoding='latin1')
    if 'blobs' in src_blobs:
        src_blobs = src_blobs['blobs']

    params = net.state_dict()
    for p_name, p_tensor in params.items():
        d_name = name_mapping[p_name]
        if d_name: # if not None of 0
            try:
                p_tensor.copy_(torch.Tensor(src_blobs[d_name]))
            except RuntimeError:
                print("Not loaded from detectron:", d_name)
```

Instead of crashing when the sizes are mismatched, I print out the names of the problematic output layers when loading fails: 

```
Not loaded from detectron: cls_score_w
Not loaded from detectron: cls_score_b
Not loaded from detectron: bbox_pred_w
Not loaded from detectron: bbox_pred_b
Not loaded from detectron: mask_fcn_logits_w
Not loaded from detectron: mask_fcn_logits_b
```

With this modification, the training code seems to be running properly. I'm just wondering if not loading the weights from detectron like this is okay? I'm not too familiar with the whole codebase, but I'm guessing the model is now just using its default initialization for the above layers instead of loading them which should be fine?

Also, since using the try-except block like this is not good practice, I'll probably filter for those layers directly and set them to ```None``` in ```detectron_weight_mapping``` function in ```lib/modeling/model_builder.py```. Maybe this could be a future feature, so that other people can easily train on their custom datasets too.

Hope this info can be useful for everyone!

**Comment by roytseng-tw** [comment]
I was a little bit wrong about 

> set the corresponding weight mapping entries to `None`

You should set those entries to `True` instead of `None`. Otherwise, you'll not load those weights from checkpoint for testing. See `lib/utils/net.py:load_ckpt`.

**Comment by vsd550** [comment]
@yimang I am also trying to train Mask Rcnn on a custom Dataset. I have **done Step 1** of the the steps provided  by u above. Can you please elaborate on the **steps 2,3 and 4** , so that I am able to successfully train my model.
Thanks in advance

**Comment by matchumen** [comment]
> Thanks for the advice!
> 
> Update: I wasn't too sure what the names of the last output layers were, so I modified the `load_detectron_weight` function in `lib/utils/detectron_weight_helper.py` by adding a try-except block:
> 
> ```python
> def load_detectron_weight(net, detectron_weight_file):
>     name_mapping, orphan_in_detectron = net.detectron_weight_mapping
> 
>     with open(detectron_weight_file, 'rb') as fp:
>         src_blobs = pickle.load(fp, encoding='latin1')
>     if 'blobs' in src_blobs:
>         src_blobs = src_blobs['blobs']
> 
>     params = net.state_dict()
>     for p_name, p_tensor in params.items():
>         d_name = name_mapping[p_name]
>         if d_name: # if not None of 0
>             try:
>                 p_tensor.copy_(torch.Tensor(src_blobs[d_name]))
>             except RuntimeError:
>                 print("Not loaded from detectron:", d_name)
> ```
> 
> Instead of crashing when the sizes are mismatched, I print out the names of the problematic output layers when loading fails:
> 
> ```
> Not loaded from detectron: cls_score_w
> Not loaded from detectron: cls_score_b
> Not loaded from detectron: bbox_pred_w
> Not loaded from detectron: bbox_pred_b
> Not loaded from detectron: mask_fcn_logits_w
> Not loaded from detectron: mask_fcn_logits_b
> ```
> 
> With this modification, the training code seems to be running properly. I'm just wondering if not loading the weights from detectron like this is okay? I'm not too familiar with the whole codebase, but I'm guessing the model is now just using its default initialization for the above layers instead of loading them which should be fine?
> 
> Also, since using the try-except block like this is not good practice, I'll probably filter for those layers directly and set them to `None` in `detectron_weight_mapping` function in `lib/modeling/model_builder.py`. Maybe this could be a future feature, so that other people can easily train on their custom datasets too.
> 
> Hope this info can be useful for everyone!

Have you managed to do what you proposed? I am stuck at the same problem. Thanks in advance.
