### ISSUE TITLE
mynn.DataParallel ? 

### ISSUE THREAD

**Issue by ayst123** [roytseng-tw/Detectron.pytorch#61]
I am curious about what is the difference between your DataParallel and official nn.DataParallel ?  Can we use official one ? like maskRCNN = DataParallel( maskRCNN ) 

Thanks.

**Comment by roytseng-tw** [comment]
https://github.com/roytseng-tw/Detectron.pytorch#my-nndataparallel
You can't just replace it with the official one, but you can modified some code to make it work with the official one.
