### ISSUE TITLE
Class Agnostic BBox Reg

### ISSUE THREAD

**Issue by rawalkhirodkar** [roytseng-tw/Detectron.pytorch#62]
Setting the MODEL.CLS_AGNOSTIC_BBOX_REG = True, gives me the following error.

`python tools/train_net_step.py --dataset coco2017 --cfg configs/e2e_mask_rcnn_R-50-FPN_1x.yaml --use_tfboard --bs 9`

> /lib/roi_data/fast_rcnn.py", line 243, in _expand_bbox_targets
>     bbox_targets[ind, start:end] = bbox_target_data[ind, 1:]
> ValueError: could not broadcast input array from shape (4) into shape (0)

I tried to fix it by updating lib/roi_data/fast_rcnn.py, def _compute_targets(ex_rois, gt_rois, labels)
 
    
    if cfg.MODEL.CLS_AGNOSTIC_BBOX_REG:
        inds = np.where(labels > 0)[0]
        labels[inds] = 1
    return np.hstack((labels[:, np.newaxis], targets)).astype(
        np.float32, copy=False)`

That leads to an error while computing the loss in fast_rcnn_heads.py 

> lib/modeling/fast_rcnn_heads.py", line 60, in fast_rcnn_losses
>     bbox_pred, bbox_targets, bbox_inside_weights, bbox_outside_weights)
>   File "/home/rawal/Desktop/detectors/original_detectron/lib/utils/net.py", line 22, in smooth_l1_loss
>     box_diff = bbox_pred - bbox_targets
> RuntimeError: The size of tensor a (4) must match the size of tensor b (8) at non-singleton dimension 1
> 

Any help appreciated.
Thanks!
### System information

* Operating system: Ubuntu 16.04
* CUDA version: 8.0
* cuDNN version: 7
* GPU models (for all devices if they are not all the same): TITAN Xp
* python version: 3.5.5
* pytorch version: 0.4.0

**Comment by roytseng-tw** [comment]
Hi, bugs are fixed in newest commit.
