### ISSUE TITLE
R-101-GN.pkl cannot download

### ISSUE THREAD

**Issue by QiaoranC** [roytseng-tw/Detectron.pytorch#65]
The link of R-101-GN.pkl shows

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>DBADBB29E53709CD</RequestId>
<HostId>
IdfdzZ4uckWE4tksodyG5Oj5nmQUm7eFvyRSomIY2IIgzSVZzkvKSITdR7rFwQXxk7aNe112FuQ=
</HostId>
</Error>

**Comment by roytseng-tw** [comment]
Thank you very much ! I have fixed it.
