### ISSUE TITLE
Question About RoiDataLoader

### ISSUE THREAD

**Issue by liu6381810** [roytseng-tw/Detectron.pytorch#67]
## PLEASE FOLLOW THESE INSTRUCTIONS BEFORE POSTING
1. Please search existing *open and closed* issues in case your issue has already been reported
2. Please try to debug the issue in case you can solve it on your own before posting

## After following steps above and agreeing to provide the detailed information requested below, you may continue with posting your issue
(**Delete this line and the text above it.**)

### Expected results

I want to the RoiDataLoader work 

### Actual results
I got the wrong information:
cannot select an axis to squeeze out which has size not equal to one

What did you observe instead?

### Detailed steps to reproduce

I found the __getitem__ in RoiDataLoader
call get_minibatch()
and get_minibatch() will return a blob
then this for-loop will crash
`for key in blobs:
            if key != 'roidb':
                blobs[key] = blobs[key].squeeze(axis=0)`
I check the get_minibatch()
found it will never get a "roidb" key and other keys will never get a axis equal to one
just like the wrong information
so could you please give me some explanation?

### System information

* Operating system: Ubuntu 16.04
* CUDA version: 8
* cuDNN version: 6
* GPU models (for all devices if they are not all the same): ?
* python version: 3.6.5
* pytorch version: 0.4.0
* Anything else that seems relevant: ?

**Comment by roytseng-tw** [comment]
Dataset？ Command ?  More information please.
