### ISSUE TITLE
KeyError: 'conv_rpn_w'

### ISSUE THREAD

**Issue by vansprosk8** [roytseng-tw/Detectron.pytorch#68]
### Hi, I am trying to visualize the training results on images

I've done these steps:
1.  Downloaded model_final.pkl from original Detectron [here](https://github.com/facebookresearch/Detectron/blob/master/GETTING_STARTED.md)
2. Modified configs:
```
RESNETS:
  IMAGENET_PRETRAINED_WEIGHTS: 'data/pretrained_model/model_final.pkl'
NUM_GPUS: 1
```
3. Started infer_simple.py

And I get this error:

```
Traceback (most recent call last):
  File "/mask-rcnn.pytorch/tools/infer_simple.py", line 176, in <module>
    main()
  File "/mask-rcnn.pytorch/tools/infer_simple.py", line 128, in main
    load_detectron_weight(maskRCNN, args.load_detectron)
  File "/mask-rcnn.pytorch/lib/utils/detectron_weight_helper.py", line 22, in load_detectron_weight
    p_tensor.copy_(torch.Tensor(src_blobs[d_name]))
KeyError: 'conv_rpn_w'
```

Does **name_mapping** function work correctly?

**Comment by roytseng-tw** [comment]
Yes name_mapping is working, and your usage is wrong. You should Load Detectron's weights by `--load_detectron ...`

**Comment by vansprosk8** [comment]
Yes, I used `--load_detectron ...`
I changed the weights file and now I get the same problem, but with another KeyError:
```
  File "/mask-rcnn.pytorch/lib/utils/detectron_weight_helper.py", line 22, in load_detectron_weight
    p_tensor.copy_(torch.Tensor(src_blobs[d_name]))
KeyError: 'cls_score_w'
```

**Comment by roytseng-tw** [comment]
You don't need to change anything, including config files.
