### ISSUE TITLE
An error when running infer_simple using the X-152-32 configuration

### ISSUE THREAD

**Issue by wmmxk** [roytseng-tw/Detectron.pytorch#71]
I was running the infer_simple.py using a pretrained Detectron model. 

_python tools/infer_simple.py --dataset coco2017 --cfg configs/e2e_mask_rcnn_X-152-32x8d-FPN-IN5k_1.44x.yaml --load_detectron ./checkpoints/model_final.pkl  --image_dir data/coco/images/test --output_dir data/coco/images/test_pred_

I run into this error which points to loading the pretrained imagenet weights. **What I can not understand is why the MaskRCNN model needs to load the imagenet weight since I feed the model_final.pkl file**. _**Besides, I did download the imagenet weight (X-152-32x8d-IN5k.pkl) but still I run into the following error.**_ (I can run the infer_simple.py using the R-101-FPN_2x.yaml setting).

 _The error I run  into:
load cfg from file: configs/e2e_mask_rcnn_X-152-32x8d-FPN-IN5k_1.44x.yaml
Traceback (most recent call last):
  File "tools/infer_simple.py", line 185, in <module>
    main()
  File "tools/infer_simple.py", line 121, in main
    maskRCNN = Generalized_RCNN()
  File "/home/wxk/Ipython/Detectron.pytorch/lib/modeling/model_builder.py", line 98, in __init__
    self._init_modules()
  File "/home/wxk/Ipython/Detectron.pytorch/lib/modeling/model_builder.py", line 102, in _init_modules
    resnet_utils.load_pretrained_imagenet_weights(self)
  File "/home/wxk/Ipython/Detectron.pytorch/lib/utils/resnet_weights_helper.py", line 20, in load_pretrained_imagenet_weights
    pretrianed_state_dict = convert_state_dict(torch.load(weights_file))_

**Comment by roytseng-tw** [comment]
The given error message is incomplete. 
BTW, augmented testing are not yet implemented. So you shouldn't be able to run `e2e_mask_rcnn_X-152-32x8d-FPN-IN5k_1.44x.yaml` without commenting out the augmented testing part.
I was able to run it by commenting out those lines in the config file.

**Comment by roytseng-tw** [comment]
@wmmxk  Hi, I have updated test code and implemented augmented testing ~
