### ISSUE TITLE
Issue infering with infer_simple.py

### ISSUE THREAD

**Issue by lp1992** [roytseng-tw/Detectron.pytorch#72]
### Expected results

Trying to use the pre-trained model to annotate some of my images.

### Actual results

Called with args:
Namespace(cfg_file='configs/baselines/e2e_mask_rcnn_R-50-C4_1x.yaml', cuda=True, dataset='coco', image_dir='/~/data/images_short/', images=None, load_ckpt='data/pretrained_models/resnet152_caffe.pth', load_detectron=None, merge_pdfs=True, output_dir='/~/data/results_short', set_cfgs=[])
load cfg from file: configs/baselines/e2e_mask_rcnn_R-50-C4_1x.yaml
Traceback (most recent call last):
  File "tools/infer_simple.py", line 176, in <module>
    main()
  File "tools/infer_simple.py", line 115, in main
    maskRCNN = Generalized_RCNN()
  File "/home/ubuntu/mask-rcnn.pytorch/lib/modeling/model_builder.py", line 115, in __init__
    self._init_modules()
  File "/home/ubuntu/mask-rcnn.pytorch/lib/modeling/model_builder.py", line 122, in _init_modules
    assert self.Mask_Head.res5.state_dict() == self.Box_Head.res5.state_dict()
RuntimeError: bool value of Tensor with more than one value is ambiguous

### Detailed steps to reproduce

Command ran: python tools/infer_simple.py --dataset coco --cfg configs/baselines/e2e_mask_rcnn_R-50-C4_1x.yaml --load_ckpt data/pretrained_models/resnet152_caffe.pth 
--image_dir /~/data/images_short/ --output_dir /~/data/results_short

### System information

* Operating system: Ubuntu 16.04
* CUDA version: 8.0
* python version: 3.6
* pytorch version: 0.4.0

**Comment by roytseng-tw** [comment]
Hello, thank you for report this bug. It's due to a behavior difference on comparing tensors on pytorch0.3.1 and pytorch0.4. I have fixed it.

**Comment by joshualmitchell** [comment]
I get the same error when training:

> python3 tools/train_net_step.py --dataset coco2017 --cfg config/baselines/e2e_mask_rcnn_R-50-C4_1x.yaml

Traceback (most recent call last):
  File "tools/train_net_step.py", line 450, in <module>
    main()
  File "tools/train_net_step.py", line 264, in main
    maskRCNN = Generalized_RCNN()
  File "/lib/modeling/model_builder.py", line 102, in __init__
    self._init_modules()
  File "/lib/modeling/model_builder.py", line 109, in _init_modules
    assert self.Mask_Head.res5.state_dict() == self.Box_Head.res5.state_dict()
RuntimeError: bool value of Tensor with more than one value is ambiguous
