### ISSUE TITLE
Compiling lib error

### ISSUE THREAD

**Issue by zhenheny** [roytseng-tw/Detectron.pytorch#73]
### Expected results

Compiling all modules in lib folder

### Actual results

build.py in each module causes problem. The error shows "error: ‘for’ loop initial declarations are only allowed in C99 mode". 

### Detailed steps to reproduce

Just clone the repo and run "sh make.sh" when in the "lib" directory

```
The command that you ran
```

"sh make.sh"

### System information

* Operating system: Ubuntu 14.04
* CUDA version: 8.0
* cuDNN version: 5.1
* GPU models (for all devices if they are not all the same): Titan X (Pascal)
* python version: 3.6
* pytorch version: 0.4.0
* Anything else that seems relevant: ?

Thank you

**Comment by zhenheny** [comment]
solved by export CFLAGS="-std=c99"

**Comment by stoneyang** [comment]
@zhenheny Thanks for sharing solution!

**Comment by bobwan1995** [comment]
Thanks a lot!

**Comment by qingfengmuye** [comment]
> export CFLAGS="-std=c99"

thanks

**Comment by spytensor** [comment]
Thanks
