### ISSUE TITLE
How to get the checkpoints in the argument --load_ckpt or --load_detectron?

### ISSUE THREAD

**Issue by vsd550** [roytseng-tw/Detectron.pytorch#76]
The checkpoints are not provided in the repo.
How do we need to proceed if we just need to make an inference?

**Comment by roytseng-tw** [comment]
You may download Detectron's trained weights from [here](https://github.com/facebookresearch/Detectron/blob/master/MODEL_ZOO.md).

**Comment by vsd550** [comment]
@roytseng-tw  I am using the following command

> python tools/infer_simple.py --dataset coco --cfg configs/baselines/e2e_mask_rcnn_R-50-C4_1x.yaml **--load_detectron {NOT_SURE}** --image_dir input_img_dir  --output_dir outputdir

In the above link provided by u, there are many weight files,etc. I am getting confused which one to download and use at --load_detectron.
Thanks for the help

**Comment by joshualmitchell** [comment]
In other words, the Detectron pretrained weights are the "checkpoints"?

I'm running this:

> python tools/test_net.py **--dataset** coco2017 **--cfg** config/baselines/test_mask_rcnn_R-50-FPN_1x.yaml **--load_ckpt** mask-rcnn.pytorch/data/pretrained_model/pkl/R-50.pkl **--multi-gpu-testing**

(test_mask_rcnn_R-50-FPN_1x.yaml is a copy of e2e_mask_rcnn_R-101-FPN_1x.yaml where I changed the number of gpus to account for my own build)

And I'm getting

AssertionError: Range subprocess failed (exit code: 1)

**Comment by nymph332088** [comment]
@joshualmitchell 
There is two possible reasons from your description
1. You downloaded the backbone weights pretrained on ImageNet.
2. You  should use --load_detectron instead of -load_ckpt 

Hope it helps.

**Comment by roytseng-tw** [comment]
@nymph332088  thanks for your reply!
