### ISSUE TITLE
_roi_pooling.so: undefined symbol: __cudaPopCallConfiguration

### ISSUE THREAD

**Issue by baiyancheng20** [roytseng-tw/Detectron.pytorch#78]
When I trained the model, I met with the following problem:
__roi_pooling.so: undefined symbol: __cudaPopCallConfiguration_

The command I used for training:
_python tools/train_net_step.py   --dataset keypoints_coco2017 --cfg configs/e2e_keypoint_rcnn_R-50-FPN_1x.yaml   --bs 8 --iter_size 2 --use_tfboard_

The system information: 
_I used CUDA 9.2 and PyTorch 0.4 for using CUDA in Python 3.6 with Ubuntu 16.04._

**Comment by roytseng-tw** [comment]
1.  Does the version of NCCL that you installed match version of CUDA?
2. Do you have other versions of CUDA installed in your system?

**Comment by baiyancheng20** [comment]
Thank you @roytseng-tw. I have solved the problem. I re-installed the pytorch with cuda 9.1 and reinstall the cuda 9.1. It works now.

**Comment by victorjdcom** [comment]
I have the same problem in conda. I used CUDA9.0 and PyTorch 0.4 Python3.6. Do we need to update to cuda9.1?

**Comment by victorjdcom** [comment]
my host machine has CUDA9.2. Will that cause this error?

**Comment by kumi123** [comment]
dose this model fit cuda10.0? i got the  same error

**Comment by QUJIJI** [comment]
@kumi123 
I used cuda 10.0 and encountered the same error. Could tell me how do you solve it?

**Comment by QUJIJI** [comment]
@kumi123 
I used cuda 10.0 and encountered the same error. Could you tell me how do you solve it?
