### ISSUE TITLE
Issues with training : Dataloader not iterable

### ISSUE THREAD

**Issue by vsd550** [roytseng-tw/Detectron.pytorch#79]
I am training the model using the following command

> python tools/train_net.py --dataset coco2017 --cfg configs/baselines/e2e_mask_rcnn_R-50-C4_1x.yaml  --bs 8 --nw 4

The dataset is getting loaded properly but I am getting an error in **line 327 on train_net.py**
_for args.step, input_data in zip(range(args.start_iter, iters_per_epoch), dataloader):_
The error says :  **The argument#2 of zip must be iterable.**

Please help. Thanks

**Comment by roytseng-tw** [comment]
`train_net.py` is deprecated. Use 'train_net_step.py` instead.
